const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Plugins.Mouse,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Mouse.Cnds.OnClick
	];
};
self.C3_JsPropNameTable = [
	{fundo1: 0},
	{Sólido: 0},
	{chao: 0},
	{Senóide: 0},
	{chao_movel: 0},
	{Asteroide1: 0},
	{Asteroide2: 0},
	{Asteroide3: 0},
	{IDPlaneta: 0},
	{PosInicialX: 0},
	{PosInicialY: 0},
	{Encaixado: 0},
	{Mercurio: 0},
	{Venus: 0},
	{Terra: 0},
	{Marte: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Luna: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite: 0},
	{Âncora: 0},
	{Sprite2: 0},
	{TxVidas: 0},
	{Teclado: 0},
	{Limo: 0},
	{TxPlanetas: 0},
	{Áudio: 0},
	{Jupiter: 0},
	{Saturno: 0},
	{Urano: 0},
	{Netuno: 0},
	{chao2: 0},
	{Projétil: 0},
	{DarAVolta: 0},
	{Misseis: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Mouse: 0},
	{FundoSistema: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{IDSlot: 0},
	{Slot2: 0},
	{Slot1: 0},
	{Slot3: 0},
	{Slot4: 0},
	{Slot5: 0},
	{Slot6: 0},
	{Slot7: 0},
	{Slot8: 0},
	{TextoAcerto: 0},
	{TextoMensagem: 0},
	{TextoFim: 0},
	{TxAviso: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{FimDeFase: 0},
	{Texto4: 0},
	{Senóide2: 0},
	{Asteroides: 0},
	{Planetas: 0},
	{ArrastarSoltar: 0},
	{FamiliaPlanetas: 0},
	{FamiliaSlots: 0},
	{Vidas: 0},
	{PlanetaColetados: 0}
];

self.InstanceType = {
	fundo1: class extends self.ITiledBackgroundInstance {},
	chao: class extends self.ISpriteInstance {},
	chao_movel: class extends self.ISpriteInstance {},
	Asteroide1: class extends self.ISpriteInstance {},
	Asteroide2: class extends self.ISpriteInstance {},
	Asteroide3: class extends self.ISpriteInstance {},
	Mercurio: class extends self.ISpriteInstance {},
	Venus: class extends self.ISpriteInstance {},
	Terra: class extends self.ISpriteInstance {},
	Marte: class extends self.ISpriteInstance {},
	Luna: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TxVidas: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	Limo: class extends self.ISpriteInstance {},
	TxPlanetas: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	Jupiter: class extends self.ISpriteInstance {},
	Saturno: class extends self.ISpriteInstance {},
	Urano: class extends self.ISpriteInstance {},
	Netuno: class extends self.ISpriteInstance {},
	chao2: class extends self.ISpriteInstance {},
	Misseis: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	FundoSistema: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Slot2: class extends self.ISpriteInstance {},
	Slot1: class extends self.ISpriteInstance {},
	Slot3: class extends self.ISpriteInstance {},
	Slot4: class extends self.ISpriteInstance {},
	Slot5: class extends self.ISpriteInstance {},
	Slot6: class extends self.ISpriteInstance {},
	Slot7: class extends self.ISpriteInstance {},
	Slot8: class extends self.ISpriteInstance {},
	TextoAcerto: class extends self.ITextInstance {},
	TextoMensagem: class extends self.ITextInstance {},
	TextoFim: class extends self.ITextInstance {},
	TxAviso: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	FimDeFase: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	Asteroides: class extends self.ISpriteInstance {},
	Planetas: class extends self.ISpriteInstance {},
	FamiliaPlanetas: class extends self.ISpriteInstance {},
	FamiliaSlots: class extends self.ISpriteInstance {}
}